### PR TITLE
Fix extension installed check for already migrated DB schema

### LINKED ISSUE #183: ExtensionIsInstalled is not set correctly on restart
ExtensionIsInstalled is not set when restarting because `dbVersion.Compare(appVersion) == 0 `

### PR DESCRIPTION
**Pull request by antekresic**
Closes #183

### CODE REVIEW

**Comment by antekresic** [comment]
@cevian would this test catch that? Checking the flag after second migration:
https://github.com/timescale/timescale-prometheus/pull/186/files#diff-84dae51ce95be25c580ac1f2b9adc643R45

Not really sure what test we could do except that.

File: pkg/pgmodel/end_to_end_tests/migrate_test.go [hunk 1]
```diff
@@ -37,6 +38,12 @@ func TestMigrateTwice(t *testing.T) {
 	}
 	testhelpers.WithDB(t, *testDatabase, testhelpers.NoSuperuser, func(db *pgxpool.Pool, t testing.TB, connectURL string) {
 		performMigrate(t, connectURL)
+		if *useExtension && !pgmodel.ExtensionIsInstalled {
+			t.Errorf("extension is not installed, expected it to be installed")
+		}
```
Comment (cevian) [inline pkg/pgmodel/end_to_end_tests/migrate_test.go:43]:
```suggestion
		}
		//reset the flag to make sure it's set correctly again.
		pgmodel.ExtensionIsInstalled = false
```
