### PR TITLE
Alignment fix for atomically accessed fields on 32-bit systems

### LINKED ISSUE #140: Panics on arm
Trying to get this to run on a Pi 4 with docker.    I built the docker  image locally and configured it to connect to a (self-built) docker instance of pg_connector, with timescaledb & pg_prometheus extensions loaded & configured in that container (both using master branch).

Configured prometheus to use remote_read/write:
```
remote_write:
  - url: 'http://192.168.0.10:9201/write'
remote_read:
  - url: 'http://192.168.0.10:9201/read'
```

However, as soon as I bring up prometheus, I get a flood of the following error in the docker logfiles.
```
connector    | 2020/07/01 12:54:06 http: panic serving 172.30.0.1:52570: runtime error: invalid memory address or nil pointer dereference
connector    | goroutine 1318 [running]:
connector    | net/http.(*conn).serve.func1(0x29b445a0)
connector    | 	/usr/local/go/src/net/http/server.go:1772 +0xf0
connector    | panic(0x7d3bf8, 0xf35700)
connector    | 	/usr/local/go/src/runtime/panic.go:973 +0x3d4
connector    | github.com/timescale/timescale-prometheus/pkg/api.Write.func1(0x9b8500, 0xe3f78c0, 0x19dbf00)
connector    | 	/go/timescale-prometheus/pkg/api/write.go:42 +0x25c
connector    | net/http.HandlerFunc.ServeHTTP(0x244fff00, 0x9b8500, 0xe3f78c0, 0x19dbf00)
connector    | 	/usr/local/go/src/net/http/server.go:2012 +0x34
connector    | main.timeHandler.func1(0x9b8500, 0xe3f78c0, 0x19dbf00)
connector    | 	/go/timescale-prometheus/cmd/timescale-prometheus/main.go:327 +0x7c
connector    | net/http.HandlerFunc.ServeHTTP(0x244fff20, 0x9b8500, 0xe3f78c0, 0x19dbf00)
connector    | 	/usr/local/go/src/net/http/server.go:2012 +0x34
connector    | net/http.(*ServeMux).ServeHTTP(0xf43388, 0x9b8500, 0xe3f78c0, 0x19dbf00)
connector    | 	/usr/local/go/src/net/http/server.go:2387 +0x16c
connector    | net/http.serverHandler.ServeHTTP(0x18a0ab0, 0x9b8500, 0xe3f78c0, 0x19dbf00)
connector    | 	/usr/local/go/src/net/http/server.go:2807 +0x88
connector    | net/http.(*conn).serve(0x29b445a0, 0x9b9ca0, 0x29b7efc0)
connector    | 	/usr/local/go/src/net/http/server.go:1895 +0x7d4
connector    | created by net/http.(*Server).Serve
connector    | 	/usr/local/go/src/net/http/server.go:2933 +0x2d0
```

### PR DESCRIPTION
**Pull request by antekresic**
Reference: https://golang.org/pkg/sync/atomic/#pkg-note-BUG

Closes #140

### CODE REVIEW

File: pkg/pgmodel/pgx.go [hunk 1]
```diff
@@ -274,12 +274,12 @@ func newPgxInserter(conn pgxConn, cache MetricCache, cfg *Cfg) (*pgxInserter, er
 }
 
 type pgxInserter struct {
+	insertedDatapoints     *int64
```
Comment (JLockerman) [inline pkg/pgmodel/pgx.go:277]: this shouldn't matter, it's allocated separately, so the only thing that matters is that it's own allocation is aligned

File: pkg/api/metrics.go [hunk 2]
```diff
@@ -6,6 +6,7 @@ import (
 )
 
 type Metrics struct {
+	LastRequestUnixNano int64
```
Comment (JLockerman) [inline pkg/api/metrics.go:9]: we should either add a comment explaining that this needs to be the first field due to atomic-access requirements, or we should allocate it in it's own heap allocation
